bSI-InfraRoom/IFC-Tunnel-Deployment

- about.md
> fixing ITA AITES link in readme

- README.md
> Changed contact names for the project

- .github/workflows/schema-check.yml
ci/cd script
Gets downloaded from my server, thus no updates will be needed here.
> introducing ci/cd reporting

- files/project_team/example_sprint_1.1.ifc
added minimalist example for sprint
All specified [here](https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/blob/main/sprints/sprint1_1.md).
> minimalist example file for sprint 1.1

- Recordings/README.md
To allow sharing the YouTube-links to recordings.
> Create README.md in recordings folder

- Recordings/README.md
> Update recordings readme w. 2nd line

- Recordings/README.md
> Updated Readme for video recordings

- .github/workflows/schema-check.yml
- files/project_team/example_sprint_1.1.ifc
- files/project_team/larswik-test.ifc
Fixes #25 
1. Project Geometric Context should be correct now
Updated the script as well to cover for two or more files changed (#31).
> Updated of the checker with correction to the action script

- files/BeverControl/BeverControl.ifc
This is the IFC file produced by Bever Control for the Sprint 1.1.
It contains:
Project
UM
Context
An actor
1. Project Unit Assignment
2. Project Representation Context
3. Project Declaration
> Bever Control Sprint 1.1

- FAQ.md
> corrected schema link to the latest action

- Recordings/README.md
> Update README.md w. calls recorded Feb 09

- sprints/sprint1_3.md
> Add Project Dataset Information link to Readme

- files/project_team/example_sprint_1.2_Georef_A.ifc
- files/project_team/example_sprint_1.2_Georef_A_scaled.ifc
- files/project_team/example_sprint_1.2_Georef_B.ifc
- files/project_team/example_sprint_1.2_Georef_C.ifc
- files/project_team/example_sprint_1.2_noGeoref.ifc
I get some serialization issues when I test the provided files.  I've suggested some fixes.
> Serialization Fixes

- files/project_team/example_sprint_1.2_Georef_B.ifc
> correcting the attributes of the geographic CRS

- Recordings/README.md
> Update of Readme for Recordings w. support calls Feb 16th 08h00

- Recordings/README.md
> Update Recordings README.md with Feb.16 video (08h00+18h00)

- sprints/sprint1_3.md
Improving sprint 1.3 documentation.
> Detailing sprint 1.3 documentation

- Recordings/README.md
> Update README.md with recordings Feb.23

- files/project_team/IFCTunnelDep1.3.ifc
Example file for sprint 1.3
Example file for sprint 1.3 first draft.
1. Project Unit Assignment (1.1)
2. Project Representation Context (1.1)
3. Project Declaration (1.1)
4. Project Classification Information (1.2)
5. Spatial Decomposition (1.2)
6. Project Global Positioning - B (1.2)
7. Project Document Information (1.3)
8. Project Dataset Information (1.3)
9. Project Library Information (1.3)
10. Project Type Definitions (1.3)
11. Project Template Definitions
Created with GeometryGymIFC_Core (0.2.11)
> Lars example file for sprint 1.3

- FAQ.md
Added more documentation to FAQ.
> FAQ update

- files/BeverControl/BeverControl.ifc
Bever Control Sprint 1.3
1. Project Document Information
2. Project Dataset Information
3. Project Library Information
4. Project Type Definitions
5. Project Template Definitions
I have implemented a proposoal for cross-section/contour interpolation using the ideas from IFC guide lines.
The source code and a brief description of the proposed method may be found at:
https://github.com/ivaroppen/IFCTunnelGuideLines[https://github.com/ivaroppen/IFCTunnelGuideLines]
Any comments on the work will be appreceated
> Bever Control Sprint 1.3

- Recordings/README.md
> Update README.md with recordings of support calls Thu Mar 2nd

- files/project_team/example_sprint_1.2_Georef_A.ifc
- files/project_team/example_sprint_1.2_Georef_C.ifc
Correcting Georef example files.
> correcting some comments, copy-paste mistakes

- Recordings/README.md
> Update README.md with KickOff 2.1 recording

- Recordings/README.md
> Update README.md with Techcall 03.16 recordings

- FAQ.md
Adding documentation for how to start for software vendors in FAQ.
> Documentation for Importing software vendors

- .gitignore
- files/Catenda/README.md
*Added Catenda folder and README
*First import report from Catenda (spoiler: all fails)
> Catenda's first commit and import report.

- Recordings/README.md
> Update README.md with support calls 03.23 recording

- sprints/sprint2_1.md
> IfcReferent nesting

- FAQ.md
> additional FAQ added

- files/RDF/rdf.xml
LandXML base file, will attach here the screenshot of internal validation.
> LandXML base file

- Recordings/README.md
> Update README.md with recordings support call 2.1 + KickOff 2.2

- Recordings/README.md
> Update README.md with support calls S2.2 Apr.20

- sprints/sprint2_3.md
> Further specification of Sprint 2.3

- Recordings/README.md
> Update README.md w. May 11 support calls

- sprints/sprint1_3.md
Introdruced numberings in sprint 1.3 documentation.
> Update sprint1_3.md update numbering

- sprints/sprint1_1.md
Introduce numbering sprint 1.1
> Update sprint1_1.md update numbering

- sprints/sprint1_2.md
Introdruce numbering sprint 1.2
> Update sprint1_2.md update numbering

- Recordings/README.md
> Update README.md w. support call May 25

- sprints/sprint2_1.md
Intodruced numbering Sprint 2.1
> Update sprint2_1.md update numbering

- sprints/sprint2_3.md
Intodruced numbering Sprint 2.3
> Update sprint2_3.md update numbering

- Recordings/README.md
> Update README.md w. recordings calls Jun.01

- Recordings/README.md
> Update README.md w. recording call Jun-8th

- Recordings/README.md
> Update README.md w. recording support calls Jun-22

- Recordings/README.md
> Update README.md w. recording calls Jun-29th

- sprints/sprint3_geo.md
Included the xlsx file from the geo domain team.
> Update sprint geometry descriptions for geo entities

- .github/workflows/schema-check.yml
Fixing "green tick" result where the checker does not conclude.
> replaced default warning with error msg

- Recordings/README.md
> Update README.md w. recording call Jul-6th

- Recordings/README.md
> Update README.md w. recording calls Jul-13

- Recordings/README.md
> Update README.md w. recording calls Jul-20

- Recordings/README.md
> Update README.md w. recording support call Aug-03

- Recordings/README.md
> Recordings 2023-08-17

- sprints/sprint2_3.md
- sprints/sprint3_exc.md
- sprints/sprint3_geo.md
- sprints/sprint3_sys.md
Merely changed the order of bullet points.
> Update sprint3_sys.md - ordering of requirements

- .github/workflows/schema-check.yml
- files/project_team/IFCTunnelDep2.1.ifc
Trying out to fix the action script.
> Action fix

- sprints/sprint2_3.md
> fixing the documentation to allow for sectioned solid horizontal geom.

- sprints/sprint3_exc.md
> removing the link to earthworks cuttings

- Recordings/README.md
> Update README.md w. recordings calls Sep-28

- Recordings/README.md
> Update README.md w. recording Oct-19

- Recordings/README.md
> Update README.md w. recording Nov 2nd

- Recordings/README.md
> Update README.md w. recording Nov 16th

- Recordings/README.md
> Update README.md w. recording support call Nov.30

- Recordings/README.md
> Update README.md w. recording calls Dec.14

- Recordings/README.md
> Update README.md w. recording calls Jan 11

- .github/workflows/schema-check.yml
- files/project_team/IFCTunnelDep2.1.ifc
- updating an action to remove deprecation warning
- handling exception throwing
> Action update - exception handling

- Recordings/README.md
> Update README.md w. recording Feb 1st

- .github/workflows/schema-check.yml
- files/project_team/example_sprint_1.1.ifc
- files/project_team/example_sprint_1.2_Georef_A.ifc
Apparently some serialization within the used action changed (or sth). I did not look into it.
> fixing action serialization
